import Head from 'next/head'
import Link from 'next/link'

export default function NotionTemplates() {
  return (
    <div>
      <Head>
        <title>Notion Templates | Codersei.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container max-w-5xl mx-auto'>
          <h1 className='my-8 text-3xl font-bold dark:text-cyan-500'>Notion Templates</h1>

        <p className="mb-8 font-normal text-gray-500 dark:text-gray-300">
            Hola
        </p>

        <p>
        <Link href="/notion/templates/1">
            <a className="px-8 btn hover:underline dark:text-gray-200">
                Template #1
            </a>
        </Link>
        </p>
            

      </div>
      
    </div>
  )
}
