/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Hero from '../components/home/Hero'
import AboutStack from '../components/home/About'

export default function About() {
  return (
    <div>
      <Head>
        <title>About me | Codersei.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='container max-w-5xl mx-auto'>
          <h1 className='my-8 text-3xl font-bold dark:text-cyan-500'>About me</h1>

        <p className="mb-8 font-normal text-gray-500 dark:text-gray-300">
            Hello, I'm Alejandro, currently living in Santiago, Chile. I have 7+ years experience in software development & IT industry as an IT Professional. 
            <span className="hidden md:inline"> I have worked with JS full stack web development building modern solutions for small and big companies.</span>
        </p>
            
        <AboutStack />

      </div>
      
    </div>
  )
}
