import Head from 'next/head'
import PostList from '../components/blog/PostList'
import RecentPosts from '../components/home/RecentPosts'
import { posts } from "../__mockups__/posts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog | Codersei.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container max-w-5xl mx-auto'>
        <h1 className='my-8 text-3xl font-bold dark:text-cyan-500'>Blog</h1>
        <PostList posts={posts} />
      </div>
      
    </div>
  )
}
