import Head from 'next/head'
import { getAllPosts } from "@/src/api";
import PostList from '../components/blog/PostList'

export default function Blog({posts}) {
  return (
    <div>
      <Head>
        <title>Blog | Codersei.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container max-w-5xl mx-auto'>
        <h1 className='my-8 text-3xl font-bold dark:text-cyan-500'>Blog</h1>
        <PostList posts={posts} />
      </div>
      
    </div>
  )
}


export async function getStaticProps() {
  let posts = await getAllPosts();

  posts = [...posts].map((post) => post.meta);

  return { props: { posts } };
}