import Head from 'next/head'

import { getAllPosts } from "@/src/api";

import Hero from '../components/home/Hero'
import LastTemplate from '../components/home/LastTemplate'
import RecentPosts from '../components/home/RecentPosts'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Welcome to Codersei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <div className='container max-w-5xl mx-auto'>

        <RecentPosts posts={posts} />

        <span className='block my-16'></span>
        
        <LastTemplate />
      </div>
      
    </div>
  )
}


export async function getStaticProps() {
  let posts = await getAllPosts();

  posts = [...posts].map((post) => post.meta);

  return { props: { posts } };
}